version: '2'

services:
  db:
    image:mariadb
    restart:always
    volumes:
      -/home/ubuntu/nextcloud/db:/var/1ib/mysq1
    environment:
      -MYSQL_ROOT_PASSWORD=root
      -MYSQL_PASSWORD=nextcloud
      -MYSQL_DATABASE=nextcloud
      -MYSQL_USER=nextcloud

  app:
    image:nextcloud
    estart:always
    ports:
      -80:80
    links:
      -db
    volumes:
      -/home/ubuntu/nextcloud/www:/var/www/html 